persistence and launch

diff --git a/reflex-app-resources/resources/bin/run b/reflex-app-resources/resources/bin/run
--- a/reflex-app-resources/resources/bin/run
+++ b/reflex-app-resources/resources/bin/run
@@ -3,6 +3,20 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 INST_DIR=$DIR/../
 LAUNCH_SCRIPT=script_name=$(basename "$0")
 
+SHARED_LIB_PATH=$INST_DIR/../shared-lib
+PRIVATE_LIB_PATH=$INST_DIR/lib
+
+if [ -d "$PRIVATE_LIB_PATH" ]; then
+    LIB_PATH=$PRIVATE_LIB_PATH
+elif [ -d "$SHARED_LIB_PATH" ]; then
+    LIB_PATH=$SHARED_LIB_PATH
+else
+    echo "could not find any of: "
+    echo "  $PRIVATE_LIB_PATH"
+    echo "  $SHARED_LIB_PATH"
+    exit 1
+fi
+
 if [ -z "${JAVA_HOME}" ]; then
     # JAVA_HOME not set (or empty) --> let's hope 'java' is on the PATH
     JAVA_EXECUTABLE=java
@@ -11,4 +25,4 @@ else
     JAVA_EXECUTABLE="${JAVA_HOME}/bin/java"
 fi
 
-"$JAVA_EXECUTABLE" -Dreflex.app.dir="$INST_DIR"  -Dreflex.launch.script=$LAUNCH_SCRIPT -jar "$INST_DIR/lib/launch.jar" "$@"
+"$JAVA_EXECUTABLE" $REFLEX_OPTS -Dreflex.app.dir="$INST_DIR"  -Dreflex.launch.script=$LAUNCH_SCRIPT -jar "$LIB_PATH/launch.jar" "$@"
